module.exports = {
    printWidth: 300,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    vueIndentScriptAndStyle: false,
    singleQuote: true,
    quoteProps: "as-needed",
    bracketSpacing: true,
    jsxBracketSameLine: true,
    bracketSameLine: true,
    trailingComma: "none",
    jsxSingleQuote: false,
    arrowParens: "always",
    insertPragma: false,
    requirePragma: false,
    proseWrap: "never",
    htmlWhitespaceSensitivity: "strict",
    endOfLine: "auto",
};
